"""dealer_module_blueprint

Revision ID: 09ad012cbe24
Revises: dd17ad53f367
Create Date: 2026-02-22 02:42:20.755780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ad012cbe24'
down_revision: Union[str, Sequence[str], None] = 'dd17ad53f367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('shops', sa.Column('stock_wheat', sa.Float(), nullable=True))
    op.add_column('shops', sa.Column('stock_rice', sa.Float(), nullable=True))
    op.add_column('shops', sa.Column('stock_sugar', sa.Float(), nullable=True))
    op.add_column('shops', sa.Column('stock_kerosene', sa.Float(), nullable=True))
    op.add_column('shops', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('otp_verified', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('cash_collected', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('payment_mode', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_users_dealer_status_district'), table_name='users', postgresql_where="(role = 'dealer'::userrole)")
    op.create_index(op.f('ix_users_license_valid_until'), 'users', ['license_valid_until'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['created_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_license_valid_until'), table_name='users')
    op.create_index(op.f('ix_users_dealer_status_district'), 'users', ['dealer_status', 'district'], unique=False, postgresql_where="(role = 'dealer'::userrole)")
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_column('transactions', 'payment_mode')
    op.drop_column('transactions', 'cash_collected')
    op.drop_column('transactions', 'otp_verified')
    op.drop_column('shops', 'updated_at')
    op.drop_column('shops', 'stock_kerosene')
    op.drop_column('shops', 'stock_sugar')
    op.drop_column('shops', 'stock_rice')
    op.drop_column('shops', 'stock_wheat')
    op.drop_column('complaints', 'resolved_at')
    # ### end Alembic commands ###
