"""enterprise_hardening

Revision ID: 641cc5b0f5b9
Revises: 09ad012cbe24
Create Date: 2026-02-22 02:52:41.975670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641cc5b0f5b9'
down_revision: Union[str, Sequence[str], None] = '09ad012cbe24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
