"""add_citizen_models

Revision ID: 6cded81f2a45
Revises: 641cc5b0f5b9
Create Date: 2026-02-22 04:25:05.978576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cded81f2a45'
down_revision: Union[str, Sequence[str], None] = '641cc5b0f5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiaries', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('beneficiaries', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('beneficiaries', sa.Column('failed_attempts', sa.Integer(), nullable=True))
    op.add_column('beneficiaries', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('beneficiaries', sa.Column('lockout_until', sa.DateTime(), nullable=True))
    op.add_column('beneficiaries', sa.Column('district', sa.String(length=50), nullable=True))
    op.add_column('beneficiaries', sa.Column('mandal', sa.String(length=50), nullable=True))
    op.add_column('shops', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('shops', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('shops', sa.Column('timings', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('shops', sa.Column('risk_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'risk_score')
    op.drop_column('shops', 'rating')
    op.drop_column('shops', 'timings')
    op.drop_column('shops', 'longitude')
    op.drop_column('shops', 'latitude')
    op.drop_column('beneficiaries', 'mandal')
    op.drop_column('beneficiaries', 'district')
    op.drop_column('beneficiaries', 'lockout_until')
    op.drop_column('beneficiaries', 'last_login')
    op.drop_column('beneficiaries', 'failed_attempts')
    op.drop_column('beneficiaries', 'is_active')
    op.drop_column('beneficiaries', 'password_hash')
    # ### end Alembic commands ###
