"""Add block_index and block_hash to complaints

Revision ID: bc13cff52bbd
Revises: 6cded81f2a45
Create Date: 2026-02-22 09:39:51.781089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc13cff52bbd'
down_revision: Union[str, Sequence[str], None] = '6cded81f2a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomalies', sa.Column('block_index', sa.Integer(), nullable=True))
    op.add_column('anomalies', sa.Column('block_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_anomalies_block_hash'), 'anomalies', ['block_hash'], unique=False)
    op.add_column('complaints', sa.Column('block_index', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('block_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_complaints_block_hash'), 'complaints', ['block_hash'], unique=False)
    op.create_index(op.f('ix_transactions_block_hash'), 'transactions', ['block_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_block_hash'), table_name='transactions')
    op.drop_index(op.f('ix_complaints_block_hash'), table_name='complaints')
    op.drop_column('complaints', 'block_hash')
    op.drop_column('complaints', 'block_index')
    op.drop_index(op.f('ix_anomalies_block_hash'), table_name='anomalies')
    op.drop_column('anomalies', 'block_hash')
    op.drop_column('anomalies', 'block_index')
    # ### end Alembic commands ###
