"""Add phase 2 models

Revision ID: dd17ad53f367
Revises: 
Create Date: 2026-02-21 19:28:09.474572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd17ad53f367'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.add_column('audits', sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audits', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('audits', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('audits', sa.Column('findings', sa.String(), nullable=True))
    op.create_foreign_key(None, 'audits', 'users', ['created_by'], ['id'])
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_constraint(None, 'audits', type_='foreignkey')
    op.drop_column('audits', 'findings')
    op.drop_column('audits', 'created_by')
    op.drop_column('audits', 'priority')
    op.drop_column('audits', 'scheduled_date')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    # ### end Alembic commands ###
