"""add risk_level to risk_scores

Revision ID: ea898d50dcae
Revises: bc13cff52bbd
Create Date: 2026-02-23 11:51:23.010409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea898d50dcae'
down_revision: Union[str, Sequence[str], None] = 'bc13cff52bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scores', sa.Column('risk_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scores', 'risk_level')
    # ### end Alembic commands ###
